# prop_5_3.py
#
# Computations for Proposition 5.3 of the paper:  J_0(144)(Q) = J_C(144)(Q) = (Z/4)^3 x (Z/24)^3.
#
# Run with:  sage -python prop_5_3.py        (about half a minute)
#
# Requires the Sage package mdsage by M. Derickx, https://github.com/koffie/mdsage (version 0.1.0),
# which implements the methods of Section 4 of
#   [DEvH+21] M. Derickx, A. Etropolski, M. van Hoeij, J. S. Morrow, D. Zureick-Brown,
#             Sporadic cubic torsion, Algebra Number Theory 15 (2021), 1837-1864.
# Install it with:  sage -pip install git+https://github.com/koffie/mdsage.git@v0.1.0
#
# Notation is as in the paper. The script verifies that
#   1. the rational cuspidal subgroup J_C(144)(Q) of J_0(144) is (Z/4)^3 x (Z/24)^3;
#   2. for Delta = <-1, 11> in (Z/144)^*, the curve X_Delta(144) has genus 25 and X_Delta(144) -> X_0(144) has degree 2;
#   3. the rational cuspidal subgroup C_Delta of J_Delta(144) is (Z/2)^2 x Z/6 x (Z/24)^4 x Z/48;
#   4. J_Delta(144)(Q)_tors = C_Delta, by the argument of [DEvH+21, Theorem 4.13], i.e. Lemma 4.12 there applied to
#      the Hecke bound of [DEvH+21, Section 4.3];
#   5. the subgroup of J_Delta(144)(Q)_tors fixed by the diamond operator <5> is Z/2 x (Z/4)^2 x (Z/24)^3, whose order
#      is #J_C(144)(Q)/2.
# For comparison it also prints the bound for #J_0(144)(Q)_tors / #J_C(144)(Q) obtained by applying the Hecke bound
# to J_0(144) directly; this bound is 32, which is why the cover X_Delta(144) is needed.

from sage.all import *
from mdsage import (rational_cuspidal_classgroup, upper_bound_index_cusps_in_JG_torsion,
                    cuspidal_rational_subgroup_mod_rational_cuspidal_subgroup)
from mdsage.cuspidal_classgroup import cuspidal_integral_structure, kill_torsion_coprime_to_q
from mdsage.maartens_sage_functions import integral_period_mapping, galois_orbits


def cusps_generate_torsion(G, bound=60):
    """
    Return True if the rational torsion of the Jacobian of X_G is generated by the Galois orbits of the cusps.

    This is the argument of the proof of [DEvH+21, Theorem 4.13]: M is the Hecke bound of [DEvH+21, Section 4.3],
    a group containing J_G(Q)_tors, C is the rational cuspidal subgroup and M' the intersection of M with the group
    generated by all cuspidal divisors. If (M/C)[p] = (M'/C)[p] for all primes p dividing #M/#C, then
    J_G(Q)_tors = C by [DEvH+21, Lemma 4.12]. The lemma also needs that the cuspidal divisor classes defined over Q
    are represented by divisors defined over Q, which is checked separately below.

    Adapted from the function do_cusps_generate_J_H_torsion in the file torsionComputations.py accompanying
    [DEvH+21], written by M. Derickx.
    """
    N = G.level()
    M = ModularSymbols(G)
    Sint = cuspidal_integral_structure(M)
    kill_mat = M.star_involution().matrix().restrict(Sint) - 1
    kill = kill_mat.transpose().change_ring(ZZ).row_module()
    for p in prime_range(3, bound):
        if N % p != 0:
            kill += kill_torsion_coprime_to_q(p, M).restrict(Sint).change_ring(ZZ).transpose().row_module()
    kill_mat = kill.matrix().transpose()
    clnr1 = kill_mat.determinant()
    clnr2 = rational_cuspidal_classgroup(G).cardinality()
    bad_primes = ZZ(clnr1 / clnr2).prime_divisors()
    d_kill_mat = kill_mat.smith_form()[0][-1, -1]
    pm = integral_period_mapping(M)
    period_images1 = [sum([M.coordinate_vector(M([c, infinity])) for c in cusps]) * pm for cusps in galois_orbits(G)]
    period_images2 = [M.coordinate_vector(M([c, infinity])) * pm for c in G.cusps() if c != Cusp(oo)]
    period_matrix2, d2 = Matrix(period_images2)._clear_denom()
    for p in bad_primes:
        pn = p ** max(d_kill_mat.valuation(p), d2.valuation(p))
        kill_p = kill + pn * kill.ambient_module()
        kill_mat_p = kill_p.matrix().transpose()
        dn = pn * d2.prime_to_m_part(p)
        Sint2 = ZZ ** Sint.rank()
        Vp = Sint2 / (pn * Sint2)
        tors_bound = Vp.hom([i.lift() * kill_mat_p for i in Vp.gens()], codomain=Vp).kernel()
        rat_csp_grp = tors_bound.submodule([dn * i for i in period_images1])
        csp_grp = Vp.submodule([dn * i for i in period_images2])
        appr_csp_grp = tors_bound.submodule([i for i in csp_grp.V().intersection(tors_bound.V()).gens()])
        if len((tors_bound / rat_csp_grp).invariants()) != len((appr_csp_grp / rat_csp_grp).invariants()):
            return False
    return True


N = 144
G0 = Gamma0(N)

# 1. the rational cuspidal subgroup of J_0(144)
C0 = rational_cuspidal_classgroup(G0)
print("J_C(144)(Q) =", C0.invariants(), "of order", C0.cardinality())
assert list(C0.invariants()) == [4, 4, 4, 24, 24, 24]

# the Hecke bound applied to J_0(144) directly does not suffice
i0 = upper_bound_index_cusps_in_JG_torsion(G0, C0.cardinality())
print("the Hecke bound only shows that #J_0(144)(Q)_tors / #J_C(144)(Q) divides", i0)

# 2. the curve X_Delta(144)
GH = GammaH(N, [-1, 11])
print("X_Delta(144): genus", GH.genus(), ", degree of X_Delta(144) -> X_0(144):", GH.index() // G0.index(), ", number of cusps:", GH.ncusps())
assert GH.genus() == 25 and GH.index() == 2 * G0.index()

# 3. the rational cuspidal subgroup of J_Delta(144)
CH = rational_cuspidal_classgroup(GH)
print("C_Delta =", CH.invariants(), "of order", CH.cardinality())
assert list(CH.invariants()) == [2, 2, 6, 24, 24, 24, 24, 48]

# 4. J_Delta(144)(Q)_tors is generated by cuspidal divisors
assert cuspidal_rational_subgroup_mod_rational_cuspidal_subgroup(GH) == ()   # cuspidal classes over Q have representatives over Q
assert cusps_generate_torsion(GH)
print("J_Delta(144)(Q)_tors = C_Delta")

# 5. the invariants under the diamond operator <5>, which acts on the cusps through a matrix in Gamma_0(144)
#    with lower right entry 5
cusps = GH.cusps()
n = len(cusps)
g = [29, 1, 144, 5]
assert 29 * 5 - 1 * 144 == 1
ZZn = ZZ ** n
perm = Matrix(ZZ, [ZZn.gen(cusps.index(GH.reduce_cusp(c.apply(g)))) for c in cusps])
assert perm != 1 and perm ** 2 == 1
f = CH.hom([CH(v.lift() * (perm - 1)) for v in CH.gens()])
fixed = f.kernel()
print("J_Delta(144)(Q)^<5> =", fixed.invariants(), "of order", fixed.cardinality())
assert list(fixed.invariants()) == [2, 4, 4, 24, 24, 24]
assert 2 * fixed.cardinality() == C0.cardinality()
print("2 * #J_Delta(144)(Q)^<5> = #J_C(144)(Q), hence J_0(144)(Q) = J_C(144)(Q), as claimed in Proposition 5.3")
